changed pipeline

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -7,7 +7,7 @@ on:
     branches: [ "master" ]
 
 env:
-  aquatracker_image: '${{ secrets.DOCKER_HUB_USERNAME }}/aquatracker-api'
+  aquatracker_image: '${{ secrets.DOCKER_HUB_USERNAME }}/aquatracker-api:${{github.sha}}'
 
 jobs:
   build:
@@ -24,6 +24,12 @@ jobs:
         run: dotnet restore
       - name: Build
         run: dotnet build --no-restore
+      - name: Replace CurrentImageTag in appsettings.json
+        run: |
+          GITHUB_SHA_SHORT=${{ github.sha }}
+          sed -i 's/"CurrentImageTag": "latest"/"CurrentImageTag": "'${GITHUB_SHA_SHORT}'"/' ./.AquaTrack.Api/appsettings.json
+      - name: Verify appsettings.json
+        run: cat ./WordFlux.ApiService/appsettings.json
       - name: Test
         run: dotnet test --no-build --verbosity normal
       - name: Create Docker Image
@@ -53,3 +59,38 @@ jobs:
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
           images: ${{ env.aquatracker_image }}
+
+  confirm_deployment_API:
+    needs: deploy
+    runs-on: ubuntu-latest
+    environment:
+      name: prod
+    
+    steps:
+      - name: Check Deployment Health
+        id: check-health
+        run: |
+          API_URL="${{ needs.deploy.outputs.API_URL }}"
+          IMAGE_TAG="${{ github.sha }}"
+
+          echo "Starting deployment health check..."
+          echo "API_URL: $API_URL"
+          echo "Expected IMAGE_TAG: $IMAGE_TAG"
+
+          for i in {1..30}; do
+            echo "Checking health of the deployed application... Attempt $i"
+            response=$(curl -s -H "Content-Type: application/json" $API_URL/health)
+            echo "Response: $response"
+
+            if echo "$response" | jq -e ".imageTag == \"$IMAGE_TAG\"" > /dev/null; then
+              echo "Deployment verification succeeded: imageTag matches."
+              exit 0
+            fi
+
+            echo "Deployment verification failed: imageTag does not match. Retrying in 10 seconds..."
+            sleep 10
+          done
+
+          echo "Deployment verification failed: imageTag did not match after 30 attempts."
+          exit 1
+        shell: bash
